spring:
    datasource:
        url: jdbc:h2:file:~/biblioteca
        username: user
        password: user
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
            path: /h2-console